spring:
  profiles:
    active: local
  config:
    import:
      - optional:classpath:secrets.yml
  application:
    name: external-service

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_signal
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        default_schema: external_schema
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 19097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


slack:
  token: xoxb-9866261027956-9866605972180-sBrNbOEkl0zUwY2IrCcYGbcI