spring:
  profiles:
    active: local
  config:
    import:
      - optional:classpath:secrets.yml
  application:
    name: external-service

  jpa:
    properties:
      hibernate:
        default_schema: external_schema
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 19097

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/


