server:
  port: 19091

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/


jwt:
  secret-key: ${KEY}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/open-api/v1/orders/**,/api/v1/orders/**
              filters:
                - RewritePath=/(open-api|api)/(?<segment>.*), /$\{segment}

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/open-api/v1/products/**,/api/v1/products/**
              filters:
                - RewritePath=/(open-api|api)/(?<segment>.*), /$\{segment}

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/open-api/v1/users/**,/api/v1/users/**
              filters:
                - RewritePath=/(open-api|api)/(?<segment>.*), /$\{segment}

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/open-api/v1/deliveries/**,/api/v1/deliveries/**
              filters:
                - RewritePath=/(open-api|api)/(?<segment>.*), /$\{segment}

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/open-api/v1/companies/**,/api/v1/companies/**
              filters:
                - RewritePath=/(open-api|api)/(?<segment>.*), /$\{segment}

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/open-api/v1/hubs/**,/api/v1/hubs/**
              filters:
                - RewritePath=/(open-api|api)/(?<segment>.*), /$\{segment}