server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/


jwt:
  secret-key: ${KEY}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/open-api/v1/orders/**,/api/v1/orders/**

            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/open-api/v1/products/**,/api/v1/products/**

            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/open-api/v1/users/**,/open-api/v1/auth/**,/api/v1/users/**

            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/open-api/v1/deliveries, /open-api/v1/deliveries/**, /api/v1/deliveries/**, /open-api/v1/managers, /open-api/v1/managers/**, /api/v1/managers/**

            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/open-api/v1/companies/**,/api/v1/companies/**

            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/open-api/v1/hubs/**,/api/v1/hubs/**

            - id: external-service
              uri: lb://external-service
              predicates:
                - Path=/open-api/v1/externals/**,/api/v1/externals/**