server:
  port: 80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:19090/eureka/

jwt:
  secret-key: ${KEY}

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
          routes:
            - id: order-service
              uri: lb://order-service
              predicates:
                - Path=/open-api/v1/orders/**,/api/v1/orders/**

            - id: order-docs
              uri: lb://order-service
              predicates:
                - Path=/orders/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /orders/(?<segment>.*)
                    replacement: /${segment}


            - id: product-service
              uri: lb://product-service
              predicates:
                - Path=/open-api/v1/products/**,/api/v1/products/**

            - id: product-docs
              uri: lb://product-service
              predicates:
                - Path=/products/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /products/(?<segment>.*)
                    replacement: /${segment}


            - id: user-service
              uri: lb://user-service
              predicates:
                - Path=/open-api/v1/users/**,/open-api/v1/auth/**,/api/v1/users/**

            - id: user-docs
              uri: lb://user-service
              predicates:
                - Path=/users/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /users/(?<segment>.*)
                    replacement: /${segment}


            - id: delivery-service
              uri: lb://delivery-service
              predicates:
                - Path=/open-api/v1/deliveries/**, /api/v1/deliveries/**

            - id: delivery-docs
              uri: lb://delivery-service
              predicates:
                - Path=/deliveries/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /deliveries/(?<segment>.*)
                    replacement: /${segment}


            - id: company-service
              uri: lb://company-service
              predicates:
                - Path=/open-api/v1/companies/**,/api/v1/companies/**

            - id: company-docs
              uri: lb://company-service
              predicates:
                - Path=/companies/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /companies/(?<segment>.*)
                    replacement: /${segment}


            - id: hub-service
              uri: lb://hub-service
              predicates:
                - Path=/open-api/v1/hubs/**,/api/v1/hubs/**

            - id: hubs-docs
              uri: lb://hub-service
              predicates:
                - Path=/hubs/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /hubs/(?<segment>.*)
                    replacement: /${segment}


            - id: external-service
              uri: lb://external-service
              predicates:
                - Path=/open-api/v1/externals/**,/api/v1/externals/**

            - id: external-docs
              uri: lb://hub-service
              predicates:
                - Path=/externals/v3/api-docs
              filters:
                - name: RewritePath
                  args:
                    regexp: /externals/(?<segment>.*)
                    replacement: /${segment}

springdoc:
  swagger-ui:
    path: /docs
    urls:
      - name: order-service
        url: /orders/v3/api-docs
      - name: product-service
        url: /products/v3/api-docs
      - name: user-service
        url: /users/v3/api-docs
      - name: delivery-service
        url: /deliveries/v3/api-docs
      - name: company-service
        url: /companies/v3/api-docs
      - name: hub-service
        url: /hubs/v3/api-docs
      - name: external-service
        url: /externals/v3/api-docs