spring:
  profiles:
    active: local
  application:
    name: delivery-service

  data:
    redis:
      host: localhost # Docker 환경이라면 컨테이너 이름 또는 IP
      port: 6380

  rabbitmq:
    host: localhost
    port: 5672 # 기본 포트 번호
    username: guest # 기본 (추후 수정 필요)
    password: guest # 기본 (추후 수정 필요)
    exchange:
      name: order-exchange # 교환기 이름
      queue:
        name: delivery-request-queue # 큐 이름
      routing:
        key: delivery.new # 라우팅 키

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        default_schema: delivery
    show-sql: true

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_signal
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

server:
  port: 19091

internal:
  hub:
    url: http://localhost:19093
  user:
    url: http://localhost:19092
  external:
    url: http://localhost:19097

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

management:
  zipkin:
    tracing:
      endpoint: "http://localhost:9411/api/v2/spans"
  tracing:
    sampling:
      probability: 1.0