version: "3.8"

services:
  db:
    image: postgres:17.6
    container_name: postgres-docker-delivery-signal
    environment:
      POSTGRES_DB: delivery-signal-user-db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: