spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_signal
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}  # user
    password: ${DB_PASSWORD}  # user1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        default_schema: users

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/

service:
  jwt:
    access:
      secret: ${KEY}
      expiration: 10800000 # 만료시간: 36000ms=1h
#    access-expiration: 10800000
#    secret-key: ${KEY}
    refresh:
      secret: ${KEY2}
      expiration: 7d # 일주일


master:
  token: "AAABnvxRVklrnYxKZ0aHgTBcXukeZygoC"