server:
  port: 19091 # 8080

spring:
  application:
    name: user

#  web:
#    mvc:
#      pathmatch:
#        matched-path-prefix: /v1

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery-signal-user-db
    username: user
    password: user1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:19090/eureka/
