spring:
  #  web:
  #    mvc:
  #      pathmatch:
  #        matched-path-prefix: /v1

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_signal
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

service:
  jwt:
    access-expiration: 10800000  # 만료시간: 36000ms=1h
    secret-key: ${JWT_SECRET_KEY}