spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_signal
    driver-class-name: org.postgresql.Driver
    username: {DB_USERNAME}
    password: {DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: false
        show_sql: false
        use_sql_comments: false
        database-platform: org.hibernate.spatial.dialect.PostgreSQLDialect
service:
  jwt:
    access-expiration: 10800000  # 만료시간: 36000ms=1h
    secret-key: ${KEY}