version: "3.8"

services:
  db:
    image: postgres:17.6
    container_name: postgres-delivery-signal
    environment:
      POSTGRES_DB: delivery-signal
      POSTGRES_USER: f1
      POSTGRES_PASSWORD: qwer1234
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: